version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/python/Dockerfile
    volumes:
      - ./application:/code
    ports:
      - "8000:8000"
      # デバッグ用ポート
      - "8080:8080"
    command: poetry run python app.py
    env_file:
      - .env

